dist: trusty

language: java
jdk:
  - oraclejdk8   

notifications:
  email: false

install:
  - ./installTileDBJava
  - gradle assemble --stacktrace --debug --info

script:
  - gradle checkFormat
  - gradle test
