dist: trusty

language: java
jdk:
  - oraclejdk8

notifications:
  email: false

before_install:
  - ./scripts/installTileDBJava.sh

install:
  - ./gradlew assemble --info

script:
  - ./gradlew checkFormat
  - ./gradlew test --info
